---
title: "MN State Senate Twitter Analysis"
author: "Luke Kolar"
date: "9/18/2020"
output: html_document
---

```{r, message = F}
# Loading necessary packages...

library(rtweet)
library(tidyverse)
library(tidytext)

```

```{r}

appname <- "MN State Legislature Analysis"

key <- "PjNwrrwVXORT3T4N14rKrjQUi"
secret <- "zoXRUIOQ3QGsW4OMzBkDnRcVuatAlROX32KaLoYsQison6sLwR"
bearertoken <- "AAAAAAAAAAAAAAAAAAAAAFFTHwEAAAAAR2iPm13VvlbUPJ8rFTSO4ZXPN8g%3Dw0GU1WOIaXrQrYYYmgdgKkIJygBfyegPPLMr14Hk2xSXsBzEod"

access_token <- "1246978112493101056-LYYBwBQ1QpNJeZ0NQwVgF4xwmvGGoz"
access_secret <- "Zdz6E3EXXISBHEym3Hg7NGCf4LsDnMFCwRlFf8G9MwMdZ"

twitter_token <- create_token(
  app = appname,
  consumer_key = key,
  consumer_secret = secret,
  access_token = access_token,
  access_secret = access_secret)

```

```{r}



tmls %>% 
  select(!c(user_id, status_id, source,
            display_text_width, reply_to_user_id,
            reply_to_status_id, reply_to_screen_name)) %>% 
  View()

senate_twitters <- read.csv("mn_senate_twitters.csv") %>% 
  rename(party = party.,
         senator = senator.name.,
         district = district.,
         official = official.,
         tag = X.official..tag.,
         link = link., 
         ver = verified.) %>% 
  select(district:ver) %>% 
  select(!X) %>% 
  filter(!is.na(district))

dfl_senate_twitters <- senate_twitters %>% 
  filter(party == "DFL", tag != "-")
r_senate_twitters <- senate_twitters %>% 
  filter(party == "R", tag != "-")

as.vector(dfl_senate_twitters$tag)
r_senate_twitters

# original functions to retrieve timelines, n = 300
dfl_tmls <- get_timelines(as.vector(dfl_senate_twitters$tag), n = 4000)
r_tmls <- get_timelines(as.vector(r_senate_twitters$tag), n = 4000)

eaton <- get_timelines("EatonSenator", n = 40000)
eaton %>% 
  summarize(min = min(created_at))


r_tmls %>% group_by(screen_name) %>% 
  summarize(followers = max(followers_count))

dfl_tmls %>% group_by(screen_name) %>% 
  filter(created_at >= "2020-08-01") %>% 
  summarize(n = n(),
            rts = sum(is_retweet),
            quotes = sum(is_quote)) %>% 
  ggplot(aes(x = screen_name, y = n)) + geom_col()

dfl_tmls %>% group_by(screen_name) %>% 
  filter(created_at >= "2020-08-01") %>% 
  summarize(n = n())

glimpse(dfl_tmls)
dfl_tmls %>% 
  select(created_at:symbols, media_type, lang, quoted_text:retweet_verified, )
  filter(created_at >= "2018-01-03")

save(dfl_tmls, file = "dfl_tmls.Rdata")
save(r_tmls, file = "r_tmls.Rdata")

colnames(dfl_tmls)

dfl_tmls <- get(load("dfl_tmls.Rdata"))
dfl_tmls %>% 
  filter(created_at >= "2018-01-03")
tweets_since_aug <- r_tmls %>% rbind(dfl_tmls) %>% 
  filter(created_at >= "2018-01-03") %>% 
  group_by(screen_name) %>% 
  summarize(tweets = n(), rts = sum(is_retweet),
            quotes = sum(is_quote),
            first.in.set = min(created_at),
            account_created_at = min(account_created_at))


  group_by(screen_name) %>% 
  summarize(first.in.set = min(created_at),
            account_created_at = min(account_created_at))
  ggplot(aes(x = first.in.set, y = 1)) + geom_point()



```

```{r}
install.packages("geojsonio")
library(geojsonio)
```

```{r}

library(rgdal)

my_spdf <- readOGR( 
  dsn = paste0(getwd(),"/S2012/"), 
  layer = "S2012",
  verbose = FALSE
)

my_spdf2 <- spTransform(my_spdf,
                      CRS("+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"))

plot(my_spdf2, col="skyblue", bg="#f2f2f2", lwd=0.25, border=0 )

class(head(my_spdf2, 2))
  mutate(district = as.character(DISTRICT))
  
library(broom)
spdf_fortified <- tidy(my_spdf2)

summary(my_spdf2)

library(sf)
my_sf <- st_as_sf(my_spdf2) %>% 
  mutate(district = as.numeric(as.character(DISTRICT)))

colnames(tweets_since_aug)

colnames(my_sf_senators)
colnames(dfl_tmls)

my_sf_senators <- my_sf %>% 
  full_join(senate_twitters, by = "district") %>% 
  full_join(tweets_since_aug, by = c("tag" = "screen_name"))

dfl_tmls %>% 
  filter(verified == "TRUE") %>% 
  group_by(screen_name) %>% 
  summarize(n = n())

st_crs(my_sf_senators)

library(rgdal)
library(raster)
library(rgeos)
library(cowplot)
library(rcartocolor)

crs(my_sf_senators)
summary(my_sf_senators)

?spTransform

inset <- ggplot(my_sf_senators, aes()) + 
  geom_sf(color = "grey30", fill = "white", lwd = 0.25) + 
  geom_rect(aes(xmin = -93.58, xmax = - 92.8, ymin = 44.7, ymax = 45.15), 
            color = "red", fill = "NA", alpha = 0.5, lwd = 0.05) + 
  theme_void()

main <- ggplot(my_sf_senators, aes(fill = tweets)) + 
  geom_sf(color = "grey30", lwd = 0.25) +
  coord_sf(xlim = c(-93.58, -92.8), ylim = c(44.7, 45.15)) + 
  theme_void() + scale_fill_gradient(low = "lightyellow", high = "lightskyblue") +
  geom_sf_text(aes(label = district), colour = "black", size = 3)

ggdraw() +
  draw_plot(main) +
  draw_plot(inset, x = 0.02, y = 0.665, width = 0.35, height = 0.35)

```





















